[program:crm_queue_default]
command=/usr/bin/php /home/your_user/public_html/crm/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --queue=default
directory=/home/your_user/public_html/crm
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=your_user
numprocs=2
redirect_stderr=true
stdout_logfile=/home/your_user/logs/crm_queue_default.log
stopwaitsecs=3600

[program:crm_queue_mail]
command=/usr/bin/php /home/your_user/public_html/crm/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --queue=mail
directory=/home/your_user/public_html/crm
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=your_user
numprocs=2
redirect_stderr=true
stdout_logfile=/home/your_user/logs/crm_queue_mail.log
stopwaitsecs=3600

[program:website_queue]
command=/usr/bin/php /home/your_user/public_html/website/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --queue=default,mail
directory=/home/your_user/public_html/website
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=your_user
numprocs=2
redirect_stderr=true
stdout_logfile=/home/your_user/logs/website_queue.log
stopwaitsecs=3600

[group:pando]
programs=crm_queue_default,crm_queue_mail,website_queue
